#!/usr/bin/env bash
# auther: Dzung042
# Auto-install 3proxy on Ubuntu (18.04/20.04/22.04)
# Features:
#  - Auto-detect IPv4 and Interface
#  - Auto-detect IPv6 /64 prefix
#  - Generates random IPv6 addresses from that prefix
#  - Configures 3proxy with 1 port per IPv6
#  - Supports HTTP or SOCKS5 (user selection)
#  - Generates unique random user/pass for EACH proxy
#  - Optimizes sysctl for high concurrency
#  - Sets up boot script to restore IPv6 addresses
#  bash proxy-install.sh

set -e

# ================= CONFIGURATION =================
VER="0.9.4"
DEB_URL="https://github.com/3proxy/3proxy/releases/download/${VER}/3proxy-${VER}.x86_64.deb"

BASE_DIR="/etc/3proxy"
HOME_DIR="/home/proxy"
CONF_DIR="${BASE_DIR}/conf"
LOG_DIR="${BASE_DIR}/logs"
COUNT_DIR="${BASE_DIR}/count"

MAIN_CFG="${BASE_DIR}/3proxy.cfg"
SERVICE_CFG="${CONF_DIR}/3proxy.cfg"
PASSWD_FILE="${CONF_DIR}/passwd"
BOOT_IFCFG="${CONF_DIR}/boot_ifconfig.sh"

PORT_START=10000
COUNT_DEFAULT=200
MAXCONN=4000
DNS_SERVER="8.8.8.8"
# ============================================================================

green(){ echo -e "\e[32m$*\e[0m"; }
yellow(){ echo -e "\e[33m$*\e[0m"; }
red(){ echo -e "\e[31m$*\e[0m"; }

random_str() { tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-12}"; }

need_root(){
  if [[ $EUID -ne 0 ]]; then
    red "Run as root: sudo bash $0"
    exit 1
  fi
}

detect_iface() {
  ip -o -4 route show to default | awk '{print $5}' | head -n1
}

detect_ipv4() {
  curl -4 -s ifconfig.me || hostname -I | awk '{print $1}'
}

detect_ipv6_prefix64() {
  local iface="$1"
  local full
  full=$(ip -6 addr show dev "$iface" scope global | awk '/inet6/{print $2}' | head -n1)
  [[ -z "$full" ]] && echo "" && return
  local addr="${full%/*}"
  echo "$addr" | awk -F: '{print $1":"$2":"$3":"$4}'
}

gen_ipv6_list() {
  local prefix="$1" count="$2"
  for _ in $(seq 1 "$count"); do
    printf "%s:%x:%x:%x:%x\n" \
      "$prefix" \
      $((RANDOM%65536)) $((RANDOM%65536)) $((RANDOM%65536)) $((RANDOM%65536))
  done
}

install_3proxy_deb(){
  green "==> Installing 3proxy from .deb release (no source build)..."
  apt update -y
  apt install -y wget curl net-tools iproute2

  cd /tmp
  wget -q "${DEB_URL}" -O "3proxy-${VER}.deb"
  dpkg -i "3proxy-${VER}.deb" || apt -f install -y
}

prepare_dirs(){
  green "==> Preparing directories..."
  mkdir -p "${CONF_DIR}" "${LOG_DIR}" "${COUNT_DIR}"
}

write_main_cfg(){
  green "==> Writing main config: ${MAIN_CFG}"

  cat <<EOF > "${MAIN_CFG}"
# ===================== 3proxy main configuration =====================
# This file defines global settings (DNS, logs, auth, ACL),
# then loads per-port service definitions from /etc/3proxy/conf/3proxy.cfg

# Cache DNS records for better performance
nscache 65536

# Upstream DNS resolver
nserver ${DNS_SERVER}

# Load service definitions from a secondary config file
config ${SERVICE_CFG}

# Monitor and reload secondary config on changes/SIGHUP
monitor ${SERVICE_CFG}

# Daily log files stored under /etc/3proxy/logs
log ${LOG_DIR}/3proxy-%y%m%d.log D

# Keep last 60 daily logs
rotate 60

# Traffic counters file
counter ${COUNT_DIR}/3proxy.3cf

# Users file (format: user:CL:pass)
users \$${PASSWD_FILE}

# Optional includes (empty unless you create these files)
include ${CONF_DIR}/counters
include ${CONF_DIR}/bandlimiters

# Require strong user/password authentication
auth strong

# Safety: block using proxy to access localhost
deny * * 127.0.0.1

# Allow outbound HTTP/HTTPS destinations for authenticated users
allow * * * 80 HTTP
allow * * * 443 HTTPS

# getconfig proxy

include ${SERVICE_CFG}

# Clear ACL list before service rules are applied
flush

# If no ACL matches after flush, allow everything (still authenticated)
allow

# Global maximum concurrent connections
maxconn ${MAXCONN}
# =====================================================================
EOF
}

write_service_cfg_bulk(){
  local mode="$1" ipv4="$2" ipv6_list_file="$3"
  local port="$PORT_START"
  local proxy_list_temp="/tmp/proxy_list.tmp"

  green "==> Writing service config (bulk IPv6): ${SERVICE_CFG}"

  # Initialize password file and temp proxy list
  : > "${PASSWD_FILE}"
  chmod 600 "${PASSWD_FILE}"
  : > "${proxy_list_temp}"

  cat <<EOF > "${SERVICE_CFG}"
# ===================== Services generated by script =====================
# One port per IPv6. Each service binds:
#   -i : server IPv4 to listen on
#   -e : outgoing IPv6 (per-port)
#   -p : port number
#   -a : require authentication
#   -6 : enable IPv6
# ======================================================================
EOF

  while read -r ip6; do
    # Generate unique credentials for this IP
    local user="user$(random_str 6)"
    local pass="$(random_str 10)"

    # Add to 3proxy password file
    echo "${user}:CL:${pass}" >> "${PASSWD_FILE}"

    # Add to temp proxy list for final output
    echo "${ipv4}:${port}:${user}:${pass}:${ip6}" >> "${proxy_list_temp}"

    if [[ "$mode" == "socks" ]]; then
      echo "#BEGIN_USER_${user}" >> "${SERVICE_CFG}"
      echo "allow ${user}" >> "${SERVICE_CFG}"
      echo "socks -6 -n -a -p${port} -i${ipv4} -e${ip6}" >> "${SERVICE_CFG}"
      echo "flush" >> "${SERVICE_CFG}"
      echo "#END_USER_${user}" >> "${SERVICE_CFG}"
    else
      echo "#BEGIN_USER_${user}" >> "${SERVICE_CFG}"
      echo "allow ${user}" >> "${SERVICE_CFG}"
      echo "proxy -6 -n -a -p${port} -i${ipv4} -e${ip6}" >> "${SERVICE_CFG}"
      echo "flush" >> "${SERVICE_CFG}"
      echo "#END_USER_${user}" >> "${SERVICE_CFG}"
    fi
    port=$((port+1))
  done < "$ipv6_list_file"
}

add_ipv6_now_and_persist(){
  local iface="$1" ipv6_list_file="$2"

  green "==> Adding IPv6 addresses to interface ${iface} now..."
  while read -r ip6; do
    ip -6 addr add "${ip6}/64" dev "${iface}" 2>/dev/null || true
  done < "$ipv6_list_file"

  green "==> Creating boot-time IPv6 restore script: ${BOOT_IFCFG}"
  cat <<EOF > "${BOOT_IFCFG}"
#!/usr/bin/env bash
set -e
IFACE="${iface}"
while read -r ip; do
  ip -6 addr add "\$ip/64" dev "\$IFACE" 2>/dev/null || true
done < "${ipv6_list_file}"
EOF
  chmod +x "${BOOT_IFCFG}"

  # Ensure systemd override folder exists
  mkdir -p /etc/systemd/system/3proxy.service.d

  # Ensure IPv6 addresses are restored before 3proxy starts
  cat <<EOF > /etc/systemd/system/3proxy.service.d/override.conf
[Service]
ExecStartPre=${BOOT_IFCFG}
EOF
}

restart_service(){
  green "==> Restarting 3proxy service..."
  systemctl daemon-reload || true
  systemctl enable 3proxy || true
  systemctl restart 3proxy
}

open_firewall(){
  local count="$1"
  local from="$PORT_START"
  local to=$((PORT_START+count-1))

  green "==> Opening UFW ports ${from}-${to}/tcp (if UFW is enabled)..."
  if command -v ufw >/dev/null 2>&1; then
    ufw allow "${from}:${to}/tcp" >/dev/null 2>&1 || true
  fi
}

write_proxy_txt(){
  mkdir -p "${HOME_DIR}"
  local ipv4="$1" ipv6_list_file="$2"
  local out="${HOME_DIR}/proxy.txt"
  local proxy_list_temp="/tmp/proxy_list.tmp"

  green "==> Writing proxy list: ${out}"
  if [[ -f "${proxy_list_temp}" ]]; then
    cat "${proxy_list_temp}" > "${out}"
  else
    red "Error: Temporary proxy list not found."
  fi

  yellow "Format: IPv4:PORT:USER:PASS:IPv6"
}

main(){
  need_root
  install_3proxy_deb
  prepare_dirs

  local iface ipv4 prefix count mode choice
  iface=$(detect_iface)
  ipv4=$(detect_ipv4)

  echo
  echo "Detected interface: ${iface}"
  echo "Detected public IPv4: ${ipv4}"
  echo

  read -rp "Enter IPv6 /64 prefix (e.g. 2001:db8:abcd:1234) [auto-detect if empty]: " prefix || true
  prefix="${prefix:-$(detect_ipv6_prefix64 "$iface")}"

  if [[ -z "$prefix" ]]; then
    red "Cannot auto-detect IPv6 prefix. Please enter it manually."
    exit 1
  fi

  read -rp "How many IPv6 proxies to create? [${COUNT_DEFAULT}]: " count || true
  count="${count:-$COUNT_DEFAULT}"

  echo
  yellow "Choose proxy type:"
  echo "  1) SOCKS5 (socket)"
  echo "  2) HTTP/HTTPS proxy"
  read -rp "Your choice [1-2]: " choice

  case "$choice" in
    1) mode="socks" ;;
    2) mode="http" ;;
    *) red "Invalid choice"; exit 1 ;;
  esac

  local ipv6_list_file="${CONF_DIR}/ipv6.list"
  gen_ipv6_list "$prefix" "$count" > "$ipv6_list_file"

  add_ipv6_now_and_persist "$iface" "$ipv6_list_file"
  write_main_cfg
  write_service_cfg_bulk "$mode" "$ipv4" "$ipv6_list_file"
  open_firewall "$count"
  restart_service
  write_proxy_txt "$ipv4" "$ipv6_list_file"

  echo
  green "==> DONE!"
  echo "IPv6 prefix : ${prefix}::/64"
  echo "Proxy type  : ${mode}"
  echo "Ports       : ${PORT_START} - $((PORT_START+count-1))"
  echo "Credentials : Per-proxy (see ${HOME_DIR}/proxy.txt)"
  echo
  echo "Test (example):"
  # Get first line from proxy.txt to show example
  local first_proxy
  first_proxy=$(head -n 1 ${HOME_DIR}/proxy.txt)
  # Format: IPv4:PORT:USER:PASS:IPv6
  local f_ipv4 f_port f_user f_pass f_ipv6
  IFS=':' read -r f_ipv4 f_port f_user f_pass f_ipv6 <<< "$first_proxy"

  if [[ "$mode" == "socks" ]]; then
    echo "curl --socks5 ${f_ipv4}:${f_port} -U ${f_user}:${f_pass} https://api64.ipify.org"
  else
    echo "curl -x http://${f_user}:${f_pass}@${f_ipv4}:${f_port} https://api64.ipify.org"
  fi
}

main "$@"
